"""Update

Revision ID: 35bc2ca7e64b
Revises: 
Create Date: 2021-10-05 14:38:23.191727

"""

# revision identifiers, used by Alembic.
revision = '35bc2ca7e64b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
