"""Update

Revision ID: 3cc9880b44af
Revises: d4c7c4fb5d2c
Create Date: 2021-09-19 20:47:45.945750

"""

# revision identifiers, used by Alembic.
revision = '3cc9880b44af'
down_revision = 'd4c7c4fb5d2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
