# noinspection SpellCheckingInspection
"""Update

Revision ID: d4c7c4fb5d2c
Revises: f554adaba42b
Create Date: 2021-09-19 20:43:47.054819

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = 'd4c7c4fb5d2c'
# noinspection SpellCheckingInspection
down_revision = 'f554adaba42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lampsdata_id', table_name='lampsdata')
    op.drop_table('lampsdata')
    op.drop_table('sensorsdata')
    op.drop_table('alertevent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # noinspection SpellCheckingInspection
    op.create_table('alertevent',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False,
                              nullable=True),
                    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('log_level', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='alertevent_pkey')
                    )
    # noinspection SpellCheckingInspection
    op.create_table('sensorsdata',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False,
                              nullable=True),
                    sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('current_light_level', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='sensorsdata_pkey')
                    )
    # noinspection SpellCheckingInspection
    op.create_table('lampsdata',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False,
                              nullable=True),
                    sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_0', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_1', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_2', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_3', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_4', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_5', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_6', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_tx_7', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_0', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_1', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_2', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_3', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_4', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_5', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_6', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('light_rx_7', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('volt_0', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_4', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_5', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_6', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_7', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_8', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('volt_9', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_0', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_1', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_2', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_3', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_4', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_5', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_6', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_7', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_8', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('temp_9', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
                    sa.Column('fails_0', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_1', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_2', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_3', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_4', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_5', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_6', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_7', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('fails_8', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_0', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_1', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_2', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_3', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_4', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_5', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_6', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('max_i_7', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_0', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_1', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_2', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_3', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_4', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_5', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_6', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_7', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('blink_rw_8', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('temp_max', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('rf_net', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('group_membership', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='lampsdata_pkey')
                    )
    op.create_index('ix_lampsdata_id', 'lampsdata', ['id'], unique=False)
    # ### end Alembic commands ###
