{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Lamp 101",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  power_consumption\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 101\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  par\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 101\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  accumulated_daily_light_integral\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 101\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  temperature[1]\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 101\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  light_rx[1]\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 101\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Lamp 99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  power_consumption\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 99\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  par\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 99\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  accumulated_daily_light_integral\nFROM lamps_data\nWHERE\n  $__timeFilter(time_created) AND\n  address = 99\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Sensor 230 PPFD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_created AS \"time\",\n  ppfd\nFROM sensors_data\nWHERE\n  $__timeFilter(time_created)\nORDER BY 1"
    }
   ]
  }
 ]
}